mock_flights = [{'type': 'flight-offer',
  'id': '1',
  'source': 'GDS',
  'instantTicketingRequired': False,
  'nonHomogeneous': False,
  'oneWay': False,
  'isUpsellOffer': False,
  'lastTicketingDate': '2025-04-30',
  'lastTicketingDateTime': '2025-04-30',
  'numberOfBookableSeats': 9,
  'itineraries': [{'duration': 'PT4H33M',
    'segments': [{'departure': {'iataCode': 'LGA',
       'terminal': 'B',
       'at': '2025-05-17T07:25:00'},
      'arrival': {'iataCode': 'DEN', 'at': '2025-05-17T09:58:00'},
      'carrierCode': 'UA',
      'number': '295',
      'aircraft': {'code': '7M8'},
      'operating': {'carrierCode': 'UA'},
      'duration': 'PT4H33M',
      'id': '2',
      'numberOfStops': 0,
      'blacklistedInEU': False}]}],
  'price': {'currency': 'USD',
   'total': '228.51',
   'base': '198.31',
   'fees': [{'amount': '0.00', 'type': 'SUPPLIER'},
    {'amount': '0.00', 'type': 'TICKETING'}],
   'grandTotal': '228.51'},
  'pricingOptions': {'fareType': ['PUBLISHED'],
   'includedCheckedBagsOnly': False},
  'validatingAirlineCodes': ['UA'],
  'travelerPricings': [{'travelerId': '1',
    'fareOption': 'STANDARD',
    'travelerType': 'ADULT',
    'price': {'currency': 'USD', 'total': '228.51', 'base': '198.31'},
    'fareDetailsBySegment': [{'segmentId': '2',
      'cabin': 'ECONOMY',
      'fareBasis': 'SAA4AHES',
      'brandedFare': 'ECONOMY',
      'brandedFareLabel': 'ECONOMY',
      'class': 'S',
      'includedCheckedBags': {'quantity': 0},
      'includedCabinBags': {'quantity': 1},
      'amenities': [{'description': 'CHECKED BAG FIRST',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'SECOND BAG',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRE RESERVED SEAT ASSIGNMENT',
        'isChargeable': False,
        'amenityType': 'PRE_RESERVED_SEAT',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRIORITY BOARDING',
        'isChargeable': True,
        'amenityType': 'TRAVEL_SERVICES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'ECONOMY TO ECONOMY PLUS',
        'isChargeable': True,
        'amenityType': 'UPGRADES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'MILEAGE ACCRUAL',
        'isChargeable': False,
        'amenityType': 'BRANDED_FARES',
        'amenityProvider': {'name': 'BrandedFare'}}]}]}]},
 {'type': 'flight-offer',
  'id': '2',
  'source': 'GDS',
  'instantTicketingRequired': False,
  'nonHomogeneous': False,
  'oneWay': False,
  'isUpsellOffer': False,
  'lastTicketingDate': '2025-04-30',
  'lastTicketingDateTime': '2025-04-30',
  'numberOfBookableSeats': 9,
  'itineraries': [{'duration': 'PT4H30M',
    'segments': [{'departure': {'iataCode': 'LGA',
       'terminal': 'B',
       'at': '2025-05-17T12:30:00'},
      'arrival': {'iataCode': 'DEN', 'at': '2025-05-17T15:00:00'},
      'carrierCode': 'UA',
      'number': '2200',
      'aircraft': {'code': '738'},
      'operating': {'carrierCode': 'UA'},
      'duration': 'PT4H30M',
      'id': '1',
      'numberOfStops': 0,
      'blacklistedInEU': False}]}],
  'price': {'currency': 'USD',
   'total': '278.52',
   'base': '244.82',
   'fees': [{'amount': '0.00', 'type': 'SUPPLIER'},
    {'amount': '0.00', 'type': 'TICKETING'}],
   'grandTotal': '278.52'},
  'pricingOptions': {'fareType': ['PUBLISHED'],
   'includedCheckedBagsOnly': False},
  'validatingAirlineCodes': ['UA'],
  'travelerPricings': [{'travelerId': '1',
    'fareOption': 'STANDARD',
    'travelerType': 'ADULT',
    'price': {'currency': 'USD', 'total': '278.52', 'base': '244.82'},
    'fareDetailsBySegment': [{'segmentId': '1',
      'cabin': 'ECONOMY',
      'fareBasis': 'WAA4AHES',
      'brandedFare': 'ECONOMY',
      'brandedFareLabel': 'ECONOMY',
      'class': 'W',
      'includedCheckedBags': {'quantity': 0},
      'includedCabinBags': {'quantity': 1},
      'amenities': [{'description': 'CHECKED BAG FIRST',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'SECOND BAG',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRE RESERVED SEAT ASSIGNMENT',
        'isChargeable': False,
        'amenityType': 'PRE_RESERVED_SEAT',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRIORITY BOARDING',
        'isChargeable': True,
        'amenityType': 'TRAVEL_SERVICES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'ECONOMY TO ECONOMY PLUS',
        'isChargeable': True,
        'amenityType': 'UPGRADES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'MILEAGE ACCRUAL',
        'isChargeable': False,
        'amenityType': 'BRANDED_FARES',
        'amenityProvider': {'name': 'BrandedFare'}}]}]}]},
 {'type': 'flight-offer',
  'id': '3',
  'source': 'GDS',
  'instantTicketingRequired': False,
  'nonHomogeneous': False,
  'oneWay': False,
  'isUpsellOffer': False,
  'lastTicketingDate': '2025-04-30',
  'lastTicketingDateTime': '2025-04-30',
  'numberOfBookableSeats': 9,
  'itineraries': [{'duration': 'PT4H33M',
    'segments': [{'departure': {'iataCode': 'LGA',
       'terminal': 'B',
       'at': '2025-05-17T15:29:00'},
      'arrival': {'iataCode': 'DEN', 'at': '2025-05-17T18:02:00'},
      'carrierCode': 'UA',
      'number': '2860',
      'aircraft': {'code': '7M8'},
      'operating': {'carrierCode': 'UA'},
      'duration': 'PT4H33M',
      'id': '3',
      'numberOfStops': 0,
      'blacklistedInEU': False}]}],
  'price': {'currency': 'USD',
   'total': '348.44',
   'base': '309.94',
   'fees': [{'amount': '0.00', 'type': 'SUPPLIER'},
    {'amount': '0.00', 'type': 'TICKETING'}],
   'grandTotal': '348.44'},
  'pricingOptions': {'fareType': ['PUBLISHED'],
   'includedCheckedBagsOnly': False},
  'validatingAirlineCodes': ['UA'],
  'travelerPricings': [{'travelerId': '1',
    'fareOption': 'STANDARD',
    'travelerType': 'ADULT',
    'price': {'currency': 'USD', 'total': '348.44', 'base': '309.94'},
    'fareDetailsBySegment': [{'segmentId': '3',
      'cabin': 'ECONOMY',
      'fareBasis': 'VAA0OHEN',
      'brandedFare': 'ECONOMY',
      'brandedFareLabel': 'ECONOMY',
      'class': 'V',
      'includedCheckedBags': {'quantity': 0},
      'includedCabinBags': {'quantity': 1},
      'amenities': [{'description': 'CHECKED BAG FIRST',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'SECOND BAG',
        'isChargeable': True,
        'amenityType': 'BAGGAGE',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRE RESERVED SEAT ASSIGNMENT',
        'isChargeable': False,
        'amenityType': 'PRE_RESERVED_SEAT',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'PRIORITY BOARDING',
        'isChargeable': True,
        'amenityType': 'TRAVEL_SERVICES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'ECONOMY TO ECONOMY PLUS',
        'isChargeable': True,
        'amenityType': 'UPGRADES',
        'amenityProvider': {'name': 'BrandedFare'}},
       {'description': 'MILEAGE ACCRUAL',
        'isChargeable': False,
        'amenityType': 'BRANDED_FARES',
        'amenityProvider': {'name': 'BrandedFare'}}]}]}]}]